name: Unit tests

on:
  push:
    branches: [ master, 'releases/**' ]
  pull_request:
    branches: [ master, 'releases/**' ]
  schedule:
  - cron: "0 4 * * *"
    
jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
          - windows-latest

    steps:
    - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      with:
        submodules: true
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: |
          3.9
          3.10
          3.11
          3.12
          3.13
          3.14
        cache: pip
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -U poetry tox-gh coverage
    - name: Run tests with tox
      run: |
        tox
        coverage xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: false
        flags: unittests
  py36:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/ubi
    steps:
    - name: Install git
      run: |
        dnf install -y git
    - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      with:
        submodules: true
    - name: Run tests using platform python (Python 3.6)
      run: |
        # We don't upload coverage, since we'd need as newer libc for codecov action
        /usr/libexec/platform-python -m venv ./py36
        . ./py36/bin/activate
        pip install -U pip
        pip install -U pytest jsonschema
        pytest
